// Code generated by go-swagger; DO NOT EDIT.

package contracts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetContractBalanceParams creates a new GetContractBalanceParams object
// with the default values initialized.
func NewGetContractBalanceParams() *GetContractBalanceParams {
	var ()
	return &GetContractBalanceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetContractBalanceParamsWithTimeout creates a new GetContractBalanceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetContractBalanceParamsWithTimeout(timeout time.Duration) *GetContractBalanceParams {
	var ()
	return &GetContractBalanceParams{

		timeout: timeout,
	}
}

// NewGetContractBalanceParamsWithContext creates a new GetContractBalanceParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetContractBalanceParamsWithContext(ctx context.Context) *GetContractBalanceParams {
	var ()
	return &GetContractBalanceParams{

		Context: ctx,
	}
}

// NewGetContractBalanceParamsWithHTTPClient creates a new GetContractBalanceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetContractBalanceParamsWithHTTPClient(client *http.Client) *GetContractBalanceParams {
	var ()
	return &GetContractBalanceParams{
		HTTPClient: client,
	}
}

/*GetContractBalanceParams contains all the parameters to send to the API endpoint
for the get contract balance operation typically these are written to a http.Request
*/
type GetContractBalanceParams struct {

	/*Contract*/
	Contract string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get contract balance params
func (o *GetContractBalanceParams) WithTimeout(timeout time.Duration) *GetContractBalanceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get contract balance params
func (o *GetContractBalanceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get contract balance params
func (o *GetContractBalanceParams) WithContext(ctx context.Context) *GetContractBalanceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get contract balance params
func (o *GetContractBalanceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get contract balance params
func (o *GetContractBalanceParams) WithHTTPClient(client *http.Client) *GetContractBalanceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get contract balance params
func (o *GetContractBalanceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContract adds the contract to the get contract balance params
func (o *GetContractBalanceParams) WithContract(contract string) *GetContractBalanceParams {
	o.SetContract(contract)
	return o
}

// SetContract adds the contract to the get contract balance params
func (o *GetContractBalanceParams) SetContract(contract string) {
	o.Contract = contract
}

// WriteToRequest writes these params to a swagger request
func (o *GetContractBalanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param contract
	if err := r.SetPathParam("contract", o.Contract); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
