// Code generated by go-swagger; DO NOT EDIT.

package contracts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetContractManagerKeyReader is a Reader for the GetContractManagerKey structure.
type GetContractManagerKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetContractManagerKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetContractManagerKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetContractManagerKeyNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetContractManagerKeyInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetContractManagerKeyOK creates a GetContractManagerKeyOK with default headers values
func NewGetContractManagerKeyOK() *GetContractManagerKeyOK {
	return &GetContractManagerKeyOK{}
}

/*GetContractManagerKeyOK handles this case with default header values.

Endpoint for contract manager key
*/
type GetContractManagerKeyOK struct {
	Payload string
}

func (o *GetContractManagerKeyOK) Error() string {
	return fmt.Sprintf("[GET /chains/main/blocks/head/context/contracts/{contract}/manager_key][%d] getContractManagerKeyOK  %+v", 200, o.Payload)
}

func (o *GetContractManagerKeyOK) GetPayload() string {
	return o.Payload
}

func (o *GetContractManagerKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetContractManagerKeyNotFound creates a GetContractManagerKeyNotFound with default headers values
func NewGetContractManagerKeyNotFound() *GetContractManagerKeyNotFound {
	return &GetContractManagerKeyNotFound{}
}

/*GetContractManagerKeyNotFound handles this case with default header values.

Not found
*/
type GetContractManagerKeyNotFound struct {
}

func (o *GetContractManagerKeyNotFound) Error() string {
	return fmt.Sprintf("[GET /chains/main/blocks/head/context/contracts/{contract}/manager_key][%d] getContractManagerKeyNotFound ", 404)
}

func (o *GetContractManagerKeyNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetContractManagerKeyInternalServerError creates a GetContractManagerKeyInternalServerError with default headers values
func NewGetContractManagerKeyInternalServerError() *GetContractManagerKeyInternalServerError {
	return &GetContractManagerKeyInternalServerError{}
}

/*GetContractManagerKeyInternalServerError handles this case with default header values.

Internal error
*/
type GetContractManagerKeyInternalServerError struct {
}

func (o *GetContractManagerKeyInternalServerError) Error() string {
	return fmt.Sprintf("[GET /chains/main/blocks/head/context/contracts/{contract}/manager_key][%d] getContractManagerKeyInternalServerError ", 500)
}

func (o *GetContractManagerKeyInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
