// Code generated by go-swagger; DO NOT EDIT.

package contracts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetContractScriptParams creates a new GetContractScriptParams object
// with the default values initialized.
func NewGetContractScriptParams() *GetContractScriptParams {
	var ()
	return &GetContractScriptParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetContractScriptParamsWithTimeout creates a new GetContractScriptParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetContractScriptParamsWithTimeout(timeout time.Duration) *GetContractScriptParams {
	var ()
	return &GetContractScriptParams{

		timeout: timeout,
	}
}

// NewGetContractScriptParamsWithContext creates a new GetContractScriptParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetContractScriptParamsWithContext(ctx context.Context) *GetContractScriptParams {
	var ()
	return &GetContractScriptParams{

		Context: ctx,
	}
}

// NewGetContractScriptParamsWithHTTPClient creates a new GetContractScriptParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetContractScriptParamsWithHTTPClient(client *http.Client) *GetContractScriptParams {
	var ()
	return &GetContractScriptParams{
		HTTPClient: client,
	}
}

/*GetContractScriptParams contains all the parameters to send to the API endpoint
for the get contract script operation typically these are written to a http.Request
*/
type GetContractScriptParams struct {

	/*Contract*/
	Contract string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get contract script params
func (o *GetContractScriptParams) WithTimeout(timeout time.Duration) *GetContractScriptParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get contract script params
func (o *GetContractScriptParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get contract script params
func (o *GetContractScriptParams) WithContext(ctx context.Context) *GetContractScriptParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get contract script params
func (o *GetContractScriptParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get contract script params
func (o *GetContractScriptParams) WithHTTPClient(client *http.Client) *GetContractScriptParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get contract script params
func (o *GetContractScriptParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContract adds the contract to the get contract script params
func (o *GetContractScriptParams) WithContract(contract string) *GetContractScriptParams {
	o.SetContract(contract)
	return o
}

// SetContract adds the contract to the get contract script params
func (o *GetContractScriptParams) SetContract(contract string) {
	o.Contract = contract
}

// WriteToRequest writes these params to a swagger request
func (o *GetContractScriptParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param contract
	if err := r.SetPathParam("contract", o.Contract); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
