// Code generated by go-swagger; DO NOT EDIT.

package contracts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetContractManagerKeyParams creates a new GetContractManagerKeyParams object
// with the default values initialized.
func NewGetContractManagerKeyParams() *GetContractManagerKeyParams {
	var ()
	return &GetContractManagerKeyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetContractManagerKeyParamsWithTimeout creates a new GetContractManagerKeyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetContractManagerKeyParamsWithTimeout(timeout time.Duration) *GetContractManagerKeyParams {
	var ()
	return &GetContractManagerKeyParams{

		timeout: timeout,
	}
}

// NewGetContractManagerKeyParamsWithContext creates a new GetContractManagerKeyParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetContractManagerKeyParamsWithContext(ctx context.Context) *GetContractManagerKeyParams {
	var ()
	return &GetContractManagerKeyParams{

		Context: ctx,
	}
}

// NewGetContractManagerKeyParamsWithHTTPClient creates a new GetContractManagerKeyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetContractManagerKeyParamsWithHTTPClient(client *http.Client) *GetContractManagerKeyParams {
	var ()
	return &GetContractManagerKeyParams{
		HTTPClient: client,
	}
}

/*GetContractManagerKeyParams contains all the parameters to send to the API endpoint
for the get contract manager key operation typically these are written to a http.Request
*/
type GetContractManagerKeyParams struct {

	/*Contract*/
	Contract string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get contract manager key params
func (o *GetContractManagerKeyParams) WithTimeout(timeout time.Duration) *GetContractManagerKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get contract manager key params
func (o *GetContractManagerKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get contract manager key params
func (o *GetContractManagerKeyParams) WithContext(ctx context.Context) *GetContractManagerKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get contract manager key params
func (o *GetContractManagerKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get contract manager key params
func (o *GetContractManagerKeyParams) WithHTTPClient(client *http.Client) *GetContractManagerKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get contract manager key params
func (o *GetContractManagerKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContract adds the contract to the get contract manager key params
func (o *GetContractManagerKeyParams) WithContract(contract string) *GetContractManagerKeyParams {
	o.SetContract(contract)
	return o
}

// SetContract adds the contract to the get contract manager key params
func (o *GetContractManagerKeyParams) SetContract(contract string) {
	o.Contract = contract
}

// WriteToRequest writes these params to a swagger request
func (o *GetContractManagerKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param contract
	if err := r.SetPathParam("contract", o.Contract); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
