// Code generated by go-swagger; DO NOT EDIT.

package contracts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetContractStorageParams creates a new GetContractStorageParams object
// with the default values initialized.
func NewGetContractStorageParams() *GetContractStorageParams {
	var ()
	return &GetContractStorageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetContractStorageParamsWithTimeout creates a new GetContractStorageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetContractStorageParamsWithTimeout(timeout time.Duration) *GetContractStorageParams {
	var ()
	return &GetContractStorageParams{

		timeout: timeout,
	}
}

// NewGetContractStorageParamsWithContext creates a new GetContractStorageParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetContractStorageParamsWithContext(ctx context.Context) *GetContractStorageParams {
	var ()
	return &GetContractStorageParams{

		Context: ctx,
	}
}

// NewGetContractStorageParamsWithHTTPClient creates a new GetContractStorageParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetContractStorageParamsWithHTTPClient(client *http.Client) *GetContractStorageParams {
	var ()
	return &GetContractStorageParams{
		HTTPClient: client,
	}
}

/*GetContractStorageParams contains all the parameters to send to the API endpoint
for the get contract storage operation typically these are written to a http.Request
*/
type GetContractStorageParams struct {

	/*Contract*/
	Contract string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get contract storage params
func (o *GetContractStorageParams) WithTimeout(timeout time.Duration) *GetContractStorageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get contract storage params
func (o *GetContractStorageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get contract storage params
func (o *GetContractStorageParams) WithContext(ctx context.Context) *GetContractStorageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get contract storage params
func (o *GetContractStorageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get contract storage params
func (o *GetContractStorageParams) WithHTTPClient(client *http.Client) *GetContractStorageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get contract storage params
func (o *GetContractStorageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContract adds the contract to the get contract storage params
func (o *GetContractStorageParams) WithContract(contract string) *GetContractStorageParams {
	o.SetContract(contract)
	return o
}

// SetContract adds the contract to the get contract storage params
func (o *GetContractStorageParams) SetContract(contract string) {
	o.Contract = contract
}

// WriteToRequest writes these params to a swagger request
func (o *GetContractStorageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param contract
	if err := r.SetPathParam("contract", o.Contract); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
