// Code generated by go-swagger; DO NOT EDIT.

package chains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetChaIDParams creates a new GetChaIDParams object
// with the default values initialized.
func NewGetChaIDParams() *GetChaIDParams {

	return &GetChaIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetChaIDParamsWithTimeout creates a new GetChaIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetChaIDParamsWithTimeout(timeout time.Duration) *GetChaIDParams {

	return &GetChaIDParams{

		timeout: timeout,
	}
}

// NewGetChaIDParamsWithContext creates a new GetChaIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetChaIDParamsWithContext(ctx context.Context) *GetChaIDParams {

	return &GetChaIDParams{

		Context: ctx,
	}
}

// NewGetChaIDParamsWithHTTPClient creates a new GetChaIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetChaIDParamsWithHTTPClient(client *http.Client) *GetChaIDParams {

	return &GetChaIDParams{
		HTTPClient: client,
	}
}

/*GetChaIDParams contains all the parameters to send to the API endpoint
for the get cha Id operation typically these are written to a http.Request
*/
type GetChaIDParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get cha Id params
func (o *GetChaIDParams) WithTimeout(timeout time.Duration) *GetChaIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cha Id params
func (o *GetChaIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cha Id params
func (o *GetChaIDParams) WithContext(ctx context.Context) *GetChaIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cha Id params
func (o *GetChaIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cha Id params
func (o *GetChaIDParams) WithHTTPClient(client *http.Client) *GetChaIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cha Id params
func (o *GetChaIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetChaIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
